"""Open Alarm Monitor: SIA Protocol.

This file contains a mapping between SIA event codes and human-readable meanings.
"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class SIAEvent:
    """A generic container for each item in the SIA event dictionary."""

    code: str  # A two character short code for the event
    name: str  # Event name
    description: str  # Longer English description of the event
    affects: Optional[
        str
    ]  # Whether the event affects a Zone, Area, User, etc. Can be None.


# Event data organised into a dictionary of SIAEvents. Data courtesy of @mikestir:
# https://github.com/mikestir/alarm-server/blob/master/alarmrx.py#L322
EVENTS = {
    "AA": SIAEvent(
        code="AA",
        name="Alarm - Panel Substitution",
        description="An attempt to substitute an alternate alarm panel for a secure panel has been made",
        affects="Condition Number",
    ),
    "AB": SIAEvent(
        code="AB",
        name="Abort",
        description="An event message was not sent due to User action",
        affects="Zone",
    ),
    "AN": SIAEvent(
        code="AN",
        name="Analog Restoral",
        description="An analog fire sensor has been restored to normal operation",
        affects="Zone",
    ),
    "AR": SIAEvent(
        code="AR",
        name="AC Restoral",
        description="AC power has been restored",
        affects=None,
    ),
    "AS": SIAEvent(
        code="AS",
        name="Analog Service",
        description="An analog fire sensor needs to be cleaned or calibrated",
        affects="Zone",
    ),
    "AT": SIAEvent(
        code="AT",
        name="AC Trouble",
        description="AC power has been failed",
        affects=None,
    ),
    "BA": SIAEvent(
        code="BA",
        name="Burglary Alarm",
        description="Burglary zone has been violated while armed",
        affects="Zone",
    ),
    "BB": SIAEvent(
        code="BB",
        name="Burglary Bypass",
        description="Burglary zone has been bypassed",
        affects="Zone",
    ),
    "BC": SIAEvent(
        code="BC",
        name="Burglary Cancel",
        description="Alarm has been cancelled by authorized user",
        affects="User",
    ),
    "BD": SIAEvent(
        code="BD",
        name="Swinger Trouble",
        description="A non-fire zone has been violated after a Swinger Shutdown on the zone",
        affects="Zone",
    ),
    "BE": SIAEvent(
        code="BE",
        name="Swinger Trouble Restore",
        description="A non-fire zone restores to normal from a Swinger Trouble state",
        affects="Zone",
    ),
    "BG": SIAEvent(
        code="BG",
        name="Unverified Event - Burglary",
        description="A point assigned to a Cross Point group has gone into alarm but the Cross Point remained normal",
        affects="Zone",
    ),
    "BH": SIAEvent(
        code="BH",
        name="Burglary Alarm Restore",
        description="Alarm condition eliminated",
        affects="Zone",
    ),
    "BJ": SIAEvent(
        code="BJ",
        name="Burglary Trouble Restore",
        description="Trouble condition eliminated",
        affects="Zone",
    ),
    "BM": SIAEvent(
        code="BM",
        name="Burglary Alarm -  Cross Point",
        description="Burglary alarm w/cross point also in alarm - alarm verified",
        affects="Zone",
    ),
    "BR": SIAEvent(
        code="BR",
        name="Burglary Restoral",
        description="Alarm/trouble condition has been eliminated",
        affects="Zone",
    ),
    "BS": SIAEvent(
        code="BS",
        name="Burglary Supervisory",
        description="Unsafe intrusion detection system condition",
        affects="Zone",
    ),
    "BT": SIAEvent(
        code="BT",
        name="Burglary Trouble",
        description="Burglary zone disabled by fault",
        affects="Zone",
    ),
    "BU": SIAEvent(
        code="BU",
        name="Burglary Unbypass",
        description="Zone bypass has been removed",
        affects="Zone",
    ),
    "BV": SIAEvent(
        code="BV",
        name="Burglary Verified",
        description="A burglary alarm has occurred and been verified within programmed conditions. (zone or point not sent)",
        affects="Area",
    ),
    "BX": SIAEvent(
        code="BX",
        name="Burglary Test",
        description="Burglary zone activated during testing",
        affects="Zone",
    ),
    "BZ": SIAEvent(
        code="BZ",
        name="Missing Supervision",
        description="A non-fire Supervisory point has gone missing",
        affects="Zone",
    ),
    "CA": SIAEvent(
        code="CA",
        name="Automatic Closing",
        description="System armed automatically",
        affects="Area",
    ),
    "CD": SIAEvent(
        code="CD",
        name="Closing Delinquent",
        description="The system has not been armed for a programmed amount of time",
        affects="Area",
    ),
    "CE": SIAEvent(
        code="CE",
        name="Closing Extend",
        description="Extend closing time",
        affects="User",
    ),
    "CF": SIAEvent(
        code="CF",
        name="Forced Closing",
        description="System armed, some zones not ready",
        affects="User",
    ),
    "CG": SIAEvent(
        code="CG",
        name="Close Area",
        description="System has been partially armed",
        affects="Area",
    ),
    "CI": SIAEvent(
        code="CI",
        name="Fail to Close",
        description="An area has not been armed at the end of the closing window",
        affects="Area",
    ),
    "CJ": SIAEvent(
        code="CJ",
        name="Late Close",
        description="An area was armed after the closing window",
        affects="User",
    ),
    "CK": SIAEvent(
        code="CK",
        name="Early Close",
        description="An area was armed before the closing window",
        affects="User",
    ),
    "CL": SIAEvent(
        code="CL",
        name="Closing Report",
        description="System armed, normal",
        affects="User",
    ),
    "CM": SIAEvent(
        code="CM",
        name="Missing Alarm - Recent Closing",
        description="A point has gone missing within 2 minutes of closing",
        affects="Zone",
    ),
    "CO": SIAEvent(
        code="CO",
        name="Command Sent",
        description="A command has been sent to an expansion/peripheral device",
        affects="Condition Number",
    ),
    "CP": SIAEvent(
        code="CP",
        name="Automatic Closing",
        description="System armed automatically",
        affects="User",
    ),
    "CQ": SIAEvent(
        code="CQ",
        name="Remote Closing",
        description="The system was armed from a remote location",
        affects="User",
    ),
    "CR": SIAEvent(
        code="CR",
        name="Recent Closing",
        description="An alarm occurred within five minutes after the system was closed",
        affects="User",
    ),
    "CS": SIAEvent(
        code="CS",
        name="Closing Keyswitch",
        description="Account has been armed by keyswitch",
        affects="Zone",
    ),
    "CT": SIAEvent(
        code="CT",
        name="Late to Open",
        description="System was not disarmed on time",
        affects="Area",
    ),
    "CW": SIAEvent(
        code="CW",
        name="Was Force Armed",
        description="Header for a force armed session, forced point msgs may follow",
        affects="Area",
    ),
    "CX": SIAEvent(
        code="CX",
        name="Custom Function Executed",
        description="The panel has executed a preprogrammed set of instructions",
        affects="Custom Function",
    ),
    "CZ": SIAEvent(
        code="CZ",
        name="Point Closing",
        description="A point, as opposed to a whole area or account, has closed",
        affects="Zone",
    ),
    "DA": SIAEvent(
        code="DA",
        name="Card Assigned",
        description="An access ID has been added to the controller",
        affects="User",
    ),
    "DB": SIAEvent(
        code="DB",
        name="Card Deleted",
        description="An access ID has been deleted from the controller",
        affects="User",
    ),
    "DC": SIAEvent(
        code="DC",
        name="Access Closed",
        description="Access to all users prohibited",
        affects="Door",
    ),
    "DD": SIAEvent(
        code="DD",
        name="Access Denied",
        description="Access denied, unknown code",
        affects="Door",
    ),
    "DE": SIAEvent(
        code="DE",
        name="Request to Enter",
        description="An access point was opened via a Request to Enter device",
        affects="Door",
    ),
    "DF": SIAEvent(
        code="DF",
        name="Door Forced",
        description="Door opened without access request",
        affects="Door",
    ),
    "DG": SIAEvent(
        code="DG",
        name="Access Granted",
        description="Door access granted",
        affects="Door",
    ),
    "DH": SIAEvent(
        code="DH",
        name="Door Left Open - Restoral",
        description="An access point in a Door Left Open state has restored",
        affects="Door",
    ),
    "DI": SIAEvent(
        code="DI",
        name="Access Denied - Passback",
        description="Access denied because credential has not exited area before attempting to re-enter same area",
        affects="Door",
    ),
    "DJ": SIAEvent(
        code="DJ",
        name="Door Forced - Trouble",
        description="An access point has been forced open in an unarmed area",
        affects="Door",
    ),
    "DK": SIAEvent(
        code="DK",
        name="Access Lockout",
        description="Access denied, known code",
        affects="Door",
    ),
    "DL": SIAEvent(
        code="DL",
        name="Door Left Open - Alarm",
        description="An open access point when open time expired in an armed area",
        affects="Door",
    ),
    "DM": SIAEvent(
        code="DM",
        name="Door Left Open - Trouble",
        description="An open access point when open time expired in an unarmed area",
        affects="Door",
    ),
    "DN": SIAEvent(
        code="DN",
        name="Door Left Open (non-alarm, non-trouble)",
        description="An access point was open when the door cycle time expired",
        affects="Door",
    ),
    "DO": SIAEvent(
        code="DO",
        name="Access Open",
        description="Access to authorized users allowed",
        affects="Door",
    ),
    "DP": SIAEvent(
        code="DP",
        name="Access Denied - Unauthorized Time",
        description="An access request was denied because the request is occurring outside the user's authorized time window(s)",
        affects="Door",
    ),
    "DQ": SIAEvent(
        code="DQ",
        name="Access Denied Unauthorized Arming State",
        description="An access request was denied because the user was not authorized in this area when the area was armed",
        affects="Door",
    ),
    "DR": SIAEvent(
        code="DR",
        name="Door Restoral",
        description="Access alarm/trouble condition eliminated",
        affects="Door",
    ),
    "DS": SIAEvent(
        code="DS",
        name="Door Station",
        description="Identifies door for next report",
        affects="Door",
    ),
    "DT": SIAEvent(
        code="DT",
        name="Access Trouble",
        description="Access system trouble",
        affects=None,
    ),
    "DU": SIAEvent(
        code="DU", name="Dealer ID", description="Dealer ID number", affects="Dealer ID"
    ),
    "DV": SIAEvent(
        code="DV",
        name="Access Denied Unauthorized Entry Level",
        description="An access request was denied because the user is not authorized in this area",
        affects="Door",
    ),
    "DW": SIAEvent(
        code="DW",
        name="Access Denied - Interlock",
        description="An access request was denied because the doors associated Interlock point is open",
        affects="Door",
    ),
    "DX": SIAEvent(
        code="DX",
        name="Request to Exit",
        description="An access point was opened via a Request to Exit device",
        affects="Door",
    ),
    "DY": SIAEvent(
        code="DY",
        name="Door Locked",
        description="The door's lock has been engaged",
        affects="Door",
    ),
    "DZ": SIAEvent(
        code="DZ",
        name="Access Denied - Door Secured",
        description="An access request was denied because the door has been placed in an Access Closed state",
        affects="Door",
    ),
    "EA": SIAEvent(
        code="EA",
        name="Exit Alarm",
        description="An exit zone remained violated at the end of the exit delay period",
        affects="Zone",
    ),
    "EE": SIAEvent(
        code="EE",
        name="Exit Error",
        description="An exit zone remained violated at the end of the exit delay period",
        affects="User",
    ),
    "EJ": SIAEvent(
        code="EJ",
        name="Expansion Tamper Restore",
        description="Expansion device tamper restoral",
        affects="Device",
    ),
    "EM": SIAEvent(
        code="EM",
        name="Expansion Device Missing",
        description="Expansion device missing",
        affects="Device",
    ),
    "EN": SIAEvent(
        code="EN",
        name="Expansion Missing Restore",
        description="Expansion device communications re-established",
        affects="Device",
    ),
    "ER": SIAEvent(
        code="ER",
        name="Expansion Restoral",
        description="Expansion device trouble eliminated",
        affects="Expander",
    ),
    "ES": SIAEvent(
        code="ES",
        name="Expansion Device Tamper",
        description="Expansion device enclosure tamper",
        affects="Device",
    ),
    "ET": SIAEvent(
        code="ET",
        name="Expansion Trouble",
        description="Expansion device trouble",
        affects="Expander",
    ),
    "EX": SIAEvent(
        code="EX",
        name="External Device Condition",
        description="A specific reportable condition is detected on an external device",
        affects="Device",
    ),
    "EZ": SIAEvent(
        code="EZ",
        name="Missing Alarm - Exit Error",
        description="A point remained missing at the end of the exit delay period",
        affects="Zone",
    ),
    "FA": SIAEvent(
        code="FA",
        name="Fire Alarm",
        description="Fire condition detected",
        affects="Zone",
    ),
    "FB": SIAEvent(
        code="FB",
        name="Fire Bypass",
        description="Zone has been bypassed",
        affects="Zone",
    ),
    "FC": SIAEvent(
        code="FC",
        name="Fire Cancel",
        description="A Fire Alarm has been cancelled by an authorized person",
        affects="Zone",
    ),
    "FG": SIAEvent(
        code="FG",
        name="Unverified Event - Fire",
        description="A point assigned to a Cross Point group has gone into alarm but the Cross Point remained normal",
        affects="Zone",
    ),
    "FH": SIAEvent(
        code="FH",
        name="Fire Alarm Restore",
        description="Alarm condition eliminated",
        affects="Zone",
    ),
    "FI": SIAEvent(
        code="FI",
        name="Fire Test Begin",
        description="The transmitter area's fire test has begun",
        affects="Area",
    ),
    "FJ": SIAEvent(
        code="FJ",
        name="Fire Trouble Restore",
        description="Trouble condition eliminated",
        affects="Zone",
    ),
    "FK": SIAEvent(
        code="FK",
        name="Fire Test End",
        description="The transmitter area's fire test has ended",
        affects="Area",
    ),
    "FL": SIAEvent(
        code="FL",
        name="Fire Alarm Silenced",
        description="The fire panel's sounder was silenced by command",
        affects="Zone",
    ),
    "FM": SIAEvent(
        code="FM",
        name="Fire Alarm - Cross Point",
        description="Fire Alarm with Cross Point also in alarm verifying the Fire Alarm",
        affects="Zone",
    ),
    "FQ": SIAEvent(
        code="FQ",
        name="Fire Supervisory Trouble Restore",
        description="A fire supervisory zone that was in trouble condition has now restored to normal",
        affects="Zone",
    ),
    "FR": SIAEvent(
        code="FR",
        name="Fire Restoral",
        description="Alarm/trouble condition has been eliminated",
        affects="Zone",
    ),
    "FS": SIAEvent(
        code="FS",
        name="Fire Supervisory",
        description="Unsafe fire detection system condition",
        affects="Zone",
    ),
    "FT": SIAEvent(
        code="FT",
        name="Fire Trouble",
        description="Zone disabled by fault",
        affects="Zone",
    ),
    "FU": SIAEvent(
        code="FU",
        name="Fire Unbypass",
        description="Bypass has been removed",
        affects="Zone",
    ),
    "FV": SIAEvent(
        code="FV",
        name="Fire Supervision Restore",
        description="A fire supervision zone that was in alarm has restored to normal",
        affects="Zone",
    ),
    "FW": SIAEvent(
        code="FW",
        name="Fire Supervisory Trouble",
        description="A fire supervisory zone is now in a trouble condition",
        affects="Zone",
    ),
    "FX": SIAEvent(
        code="FX",
        name="Fire Test",
        description="Fire zone activated during test",
        affects="Zone",
    ),
    "FY": SIAEvent(
        code="FY",
        name="Missing Fire Trouble",
        description="A fire point is now logically missing",
        affects="Zone",
    ),
    "FZ": SIAEvent(
        code="FZ",
        name="Missing Fire Supervision",
        description="A Fire Supervisory point has gone missing",
        affects="Zone",
    ),
    "GA": SIAEvent(
        code="GA",
        name="Gas Alarm",
        description="Gas alarm condition detected",
        affects="Zone",
    ),
    "GB": SIAEvent(
        code="GB",
        name="Gas Bypass",
        description="Zone has been bypassed",
        affects="Zone",
    ),
    "GH": SIAEvent(
        code="GH",
        name="Gas Alarm Restore",
        description="Alarm condition eliminated",
        affects="Zone",
    ),
    "GJ": SIAEvent(
        code="GJ",
        name="Gas Trouble Restore",
        description="Trouble condition eliminated",
        affects="Zone",
    ),
    "GR": SIAEvent(
        code="GR",
        name="Gas Restoral",
        description="Alarm/trouble condition has been eliminated",
        affects="Zone",
    ),
    "GS": SIAEvent(
        code="GS",
        name="Gas Supervisory",
        description="Unsafe gas detection system condition",
        affects="Zone",
    ),
    "GT": SIAEvent(
        code="GT",
        name="Gas Trouble",
        description="Zone disabled by fault",
        affects="Zone",
    ),
    "GU": SIAEvent(
        code="GU",
        name="Gas Unbypass",
        description="Bypass has been removed",
        affects="Zone",
    ),
    "GX": SIAEvent(
        code="GX",
        name="Gas Test",
        description="Zone activated during test",
        affects="Zone",
    ),
    "HA": SIAEvent(
        code="HA",
        name="Holdup Alarm",
        description="Silent alarm, user under duress",
        affects="Zone",
    ),
    "HB": SIAEvent(
        code="HB",
        name="Holdup Bypass",
        description="Zone has been bypassed",
        affects="Zone",
    ),
    "HH": SIAEvent(
        code="HH",
        name="Holdup Alarm Restore",
        description="Alarm condition eliminated",
        affects="Zone",
    ),
    "HJ": SIAEvent(
        code="HJ",
        name="Holdup Trouble Restore",
        description="Trouble condition eliminated",
        affects="Zone",
    ),
    "HR": SIAEvent(
        code="HR",
        name="Holdup Restoral",
        description="Alarm/trouble condition has been eliminated",
        affects="Zone",
    ),
    "HS": SIAEvent(
        code="HS",
        name="Holdup Supervisory",
        description="Unsafe holdup system condition",
        affects="Zone",
    ),
    "HT": SIAEvent(
        code="HT",
        name="Holdup Trouble",
        description="Zone disabled by fault",
        affects="Zone",
    ),
    "HU": SIAEvent(
        code="HU",
        name="Holdup Unbypass",
        description="Bypass has been removed",
        affects="Zone",
    ),
    "IA": SIAEvent(
        code="IA",
        name="Equipment Failure Condition",
        description="A specific, reportable condition is detected on a device",
        affects="Zone",
    ),
    "IR": SIAEvent(
        code="IR",
        name="Equipment Fail - Restoral",
        description="The equipment condition has been restored to normal",
        affects="Zone",
    ),
    "JA": SIAEvent(
        code="JA",
        name="User Code Tamper",
        description="Too many unsuccessful attempts have been made to enter a user ID",
        affects="Area",
    ),
    "JD": SIAEvent(
        code="JD",
        name="Date Changed",
        description="The date was changed in the transmitter/receiver",
        affects="User",
    ),
    "JH": SIAEvent(
        code="JH",
        name="Holiday Changed",
        description="The transmitter's holiday schedule has been changed",
        affects="User",
    ),
    "JK": SIAEvent(
        code="JK",
        name="Latchkey Alert",
        description="A designated user passcode has not been entered during a scheduled time window",
        affects="User",
    ),
    "JL": SIAEvent(
        code="JL",
        name="Log Threshold",
        description="The transmitter's log memory has reached its threshold level",
        affects=None,
    ),
    "JO": SIAEvent(
        code="JO",
        name="Log Overflow",
        description="The transmitter's log memory has overflowed",
        affects=None,
    ),
    "JP": SIAEvent(
        code="JP",
        name="User On Premises",
        description="A designated user passcode has been used to gain access to the premises.",
        affects="User",
    ),
    "JR": SIAEvent(
        code="JR",
        name="Schedule Executed",
        description="An automatic scheduled event was executed",
        affects="Area",
    ),
    "JS": SIAEvent(
        code="JS",
        name="Schedule Changed",
        description="An automatic schedule was changed",
        affects="User",
    ),
    "JT": SIAEvent(
        code="JT",
        name="Time Changed",
        description="The time was changed in the transmitter/receiver",
        affects="User",
    ),
    "JV": SIAEvent(
        code="JV",
        name="User Code Changed",
        description="A user's code has been changed",
        affects="User",
    ),
    "JX": SIAEvent(
        code="JX",
        name="User Code Deleted",
        description="A user's code has been removed",
        affects="User",
    ),
    "JY": SIAEvent(
        code="JY",
        name="User Code Added",
        description="A user's code has been added",
        affects="User",
    ),
    "JZ": SIAEvent(
        code="JZ",
        name="User Level Set",
        description="A user's authority level has been set",
        affects="User",
    ),
    "KA": SIAEvent(
        code="KA",
        name="Heat Alarm",
        description="High temperature detected on premise",
        affects="Zone",
    ),
    "KB": SIAEvent(
        code="KB",
        name="Heat Bypass",
        description="Zone has been bypassed",
        affects="Zone",
    ),
    "KH": SIAEvent(
        code="KH",
        name="Heat Alarm Restore",
        description="Alarm condition eliminated",
        affects="Zone",
    ),
    "KJ": SIAEvent(
        code="KJ",
        name="Heat Trouble Restore",
        description="Trouble condition eliminated",
        affects="Zone",
    ),
    "KR": SIAEvent(
        code="KR",
        name="Heat Restoral",
        description="Alarm/trouble condition has been eliminated",
        affects="Zone",
    ),
    "KS": SIAEvent(
        code="KS",
        name="Heat Supervisory",
        description="Unsafe heat detection system condition",
        affects="Zone",
    ),
    "KT": SIAEvent(
        code="KT",
        name="Heat Trouble",
        description="Zone disabled by fault",
        affects="Zone",
    ),
    "KU": SIAEvent(
        code="KU",
        name="Heat Unbypass",
        description="Bypass has been removed",
        affects="Zone",
    ),
    "LB": SIAEvent(
        code="LB",
        name="Local Program",
        description="Begin local programming",
        affects=None,
    ),
    "LD": SIAEvent(
        code="LD",
        name="Local Program Denied",
        description="Access code incorrect",
        affects=None,
    ),
    "LE": SIAEvent(
        code="LE",
        name="Listen-in Ended",
        description="The listen-in session has been terminated",
        affects=None,
    ),
    "LF": SIAEvent(
        code="LF",
        name="Listen-in Begin",
        description="The listen-in session with the RECEIVER has begun",
        affects=None,
    ),
    "LR": SIAEvent(
        code="LR",
        name="Phone Line Restoral",
        description="Phone line restored to service",
        affects="Line",
    ),
    "LS": SIAEvent(
        code="LS",
        name="Local Program Success",
        description="Local programming successful",
        affects=None,
    ),
    "LT": SIAEvent(
        code="LT",
        name="Phone Line Trouble",
        description="Phone line trouble report",
        affects="Line",
    ),
    "LU": SIAEvent(
        code="LU",
        name="Local Program Fail",
        description="Local programming unsuccessful",
        affects=None,
    ),
    "LX": SIAEvent(
        code="LX",
        name="Local Programming Ended",
        description="A local programming session has been terminated",
        affects=None,
    ),
    "MA": SIAEvent(
        code="MA",
        name="Medical Alarm",
        description="Emergency assistance request",
        affects="Zone",
    ),
    "MB": SIAEvent(
        code="MB",
        name="Medical Bypass",
        description="Zone has been bypassed",
        affects="Zone",
    ),
    "MH": SIAEvent(
        code="MH",
        name="Medical Alarm Restore",
        description="Alarm condition eliminated",
        affects="Zone",
    ),
    "MI": SIAEvent(
        code="MI",
        name="Message",
        description="A canned message is being sent",
        affects="Message",
    ),
    "MJ": SIAEvent(
        code="MJ",
        name="Medical Trouble Restore",
        description="Trouble condition eliminated",
        affects="Zone",
    ),
    "MR": SIAEvent(
        code="MR",
        name="Medical Restoral",
        description="Alarm/trouble condition has been eliminated",
        affects="Zone",
    ),
    "MS": SIAEvent(
        code="MS",
        name="Medical Supervisory",
        description="Unsafe system condition exists",
        affects="Zone",
    ),
    "MT": SIAEvent(
        code="MT",
        name="Medical Trouble",
        description="Zone disabled by fault",
        affects="Zone",
    ),
    "MU": SIAEvent(
        code="MU",
        name="Medical Unbypass",
        description="Bypass has been removed",
        affects="Zone",
    ),
    "NA": SIAEvent(
        code="NA",
        name="No Activity",
        description="There has been no zone activity for a programmed amount of time",
        affects="Zone",
    ),
    "NC": SIAEvent(
        code="NC",
        name="Network Condition",
        description="A communications network has a specific reportable condition",
        affects="Network",
    ),
    "NF": SIAEvent(
        code="NF",
        name="Forced Perimeter Arm",
        description="Some zones/points not ready",
        affects="Area",
    ),
    "NL": SIAEvent(
        code="NL",
        name="Perimeter Armed",
        description="An area has been perimeter armed",
        affects="Area",
    ),
    "NM": SIAEvent(
        code="NM",
        name="Perimeter Armed, User Defined",
        description="A user defined area has been perimeter armed",
        affects="Area",
    ),
    "NR": SIAEvent(
        code="NR",
        name="Network Restoral",
        description="A communications network has returned to normal operation",
        affects="Network",
    ),
    "NS": SIAEvent(
        code="NS",
        name="Activity Resumed",
        description="A zone has detected activity after an alert",
        affects="Zone",
    ),
    "NT": SIAEvent(
        code="NT",
        name="Network Failure",
        description="A communications network has failed",
        affects="Network",
    ),
    "OA": SIAEvent(
        code="OA",
        name="Automatic Opening",
        description="System has disarmed automatically",
        affects="Area",
    ),
    "OC": SIAEvent(
        code="OC",
        name="Cancel Report",
        description="Untyped zone cancel",
        affects="User",
    ),
    "OG": SIAEvent(
        code="OG",
        name="Open Area",
        description="System has been partially disarmed",
        affects="Area",
    ),
    "OH": SIAEvent(
        code="OH",
        name="Early to Open from Alarm",
        description="An area in alarm was disarmed before the opening window",
        affects="User",
    ),
    "OI": SIAEvent(
        code="OI",
        name="Fail to Open",
        description="An area has not been armed at the end of the opening window",
        affects="Area",
    ),
    "OJ": SIAEvent(
        code="OJ",
        name="Late Open",
        description="An area was disarmed after the opening window",
        affects="User",
    ),
    "OK": SIAEvent(
        code="OK",
        name="Early Open",
        description="An area was disarmed before the opening window",
        affects="User",
    ),
    "OL": SIAEvent(
        code="OL",
        name="Late to Open from Alarm",
        description="An area in alarm was disarmed after the opening window",
        affects="User",
    ),
    "OP": SIAEvent(
        code="OP",
        name="Opening Report",
        description="Account was disarmed",
        affects="User",
    ),
    "OQ": SIAEvent(
        code="OQ",
        name="Remote Opening",
        description="The system was disarmed from a remote location",
        affects="User",
    ),
    "OR": SIAEvent(
        code="OR",
        name="Disarm From Alarm",
        description="Account in alarm was reset/disarmed",
        affects="User",
    ),
    "OS": SIAEvent(
        code="OS",
        name="Opening Keyswitch",
        description="Account has been disarmed by keyswitch",
        affects="Zone",
    ),
    "OT": SIAEvent(
        code="OT",
        name="Late To Close",
        description="System was not armed on time",
        affects="User",
    ),
    "OU": SIAEvent(
        code="OU",
        name="Output State - Trouble",
        description="An output on a peripheral device or NAC is not functioning",
        affects="Output",
    ),
    "OV": SIAEvent(
        code="OV",
        name="Output State - Restore",
        description="An output on a peripheral device or NAC is back to normal operation",
        affects="Output",
    ),
    "OZ": SIAEvent(
        code="OZ",
        name="Point Opening",
        description="A point, rather than a full area or account, disarmed",
        affects="Zone",
    ),
    "PA": SIAEvent(
        code="PA",
        name="Panic Alarm",
        description="Emergency assistance request, manually activated",
        affects="Zone",
    ),
    "PB": SIAEvent(
        code="PB",
        name="Panic Bypass",
        description="Panic zone has been bypassed",
        affects="Zone",
    ),
    "PH": SIAEvent(
        code="PH",
        name="Panic Alarm Restore",
        description="Alarm condition eliminated",
        affects="Zone",
    ),
    "PJ": SIAEvent(
        code="PJ",
        name="Panic Trouble Restore",
        description="Trouble condition eliminated",
        affects="Zone",
    ),
    "PR": SIAEvent(
        code="PR",
        name="Panic Restoral",
        description="Alarm/trouble condition has been eliminated",
        affects="Zone",
    ),
    "PS": SIAEvent(
        code="PS",
        name="Panic Supervisory",
        description="Unsafe system condition exists",
        affects="Zone",
    ),
    "PT": SIAEvent(
        code="PT",
        name="Panic Trouble",
        description="Zone disabled by fault",
        affects="Zone",
    ),
    "PU": SIAEvent(
        code="PU",
        name="Panic Unbypass",
        description="Panic zone bypass has been removed",
        affects="Zone",
    ),
    "QA": SIAEvent(
        code="QA",
        name="Emergency Alarm",
        description="Emergency assistance request",
        affects="Zone",
    ),
    "QB": SIAEvent(
        code="QB",
        name="Emergency Bypass",
        description="Zone has been bypassed",
        affects="Zone",
    ),
    "QH": SIAEvent(
        code="QH",
        name="Emergency Alarm Restore",
        description="Alarm condition has been eliminated",
        affects="Zone",
    ),
    "QJ": SIAEvent(
        code="QJ",
        name="Emergency Trouble Restore",
        description="Trouble condition has been eliminated",
        affects="Zone",
    ),
    "QR": SIAEvent(
        code="QR",
        name="Emergency Restoral",
        description="Alarm/trouble condition has been eliminated",
        affects="Zone",
    ),
    "QS": SIAEvent(
        code="QS",
        name="Emergency Supervisory",
        description="Unsafe system condition exists",
        affects="Zone",
    ),
    "QT": SIAEvent(
        code="QT",
        name="Emergency Trouble",
        description="Zone disabled by fault",
        affects="Zone",
    ),
    "QU": SIAEvent(
        code="QU",
        name="Emergency Unbypass",
        description="Bypass has been removed",
        affects="Zone",
    ),
    "RA": SIAEvent(
        code="RA",
        name="Remote Programmer  Call Failed",
        description="Transmitter failed to communicate with the remote programmer",
        affects=None,
    ),
    "RB": SIAEvent(
        code="RB",
        name="Remote Program Begin",
        description="Remote programming session initiated",
        affects=None,
    ),
    "RC": SIAEvent(
        code="RC",
        name="Relay Close",
        description="A relay has energized",
        affects="Relay",
    ),
    "RD": SIAEvent(
        code="RD",
        name="Remote Program Denied",
        description="Access passcode incorrect",
        affects=None,
    ),
    "RN": SIAEvent(
        code="RN",
        name="Remote Reset",
        description="A TRANSMITTER was reset via a remote programmer",
        affects=None,
    ),
    "RO": SIAEvent(
        code="RO",
        name="Relay Open",
        description="A relay has de-energized",
        affects="Relay",
    ),
    "RP": SIAEvent(
        code="RP",
        name="Automatic Test",
        description="Automatic communication test report",
        affects=None,
    ),
    "RR": SIAEvent(
        code="RR",
        name="Power Up",
        description="System lost power, is now restored",
        affects=None,
    ),
    "RS": SIAEvent(
        code="RS",
        name="Remote Program Success",
        description="Remote programming successful",
        affects=None,
    ),
    "RT": SIAEvent(
        code="RT",
        name="Data Lost",
        description="Dialer data lost, transmission error",
        affects="Line",
    ),
    "RU": SIAEvent(
        code="RU",
        name="Remote Program Fail",
        description="Remote programming unsuccessful",
        affects=None,
    ),
    "RX": SIAEvent(
        code="RX",
        name="Manual Test",
        description="Manual communication test report",
        affects="User",
    ),
    "RY": SIAEvent(
        code="RY",
        name="Test Off Normal",
        description="Test signal(s) indicates abnormal condition(s) exist",
        affects="Zone",
    ),
    "SA": SIAEvent(
        code="SA",
        name="Sprinkler Alarm",
        description="Sprinkler flow condition exists",
        affects="Zone",
    ),
    "SB": SIAEvent(
        code="SB",
        name="Sprinkler Bypass",
        description="Sprinkler zone has been bypassed",
        affects="Zone",
    ),
    "SC": SIAEvent(
        code="SC",
        name="Change of State",
        description="An expansion/peripheral device is reporting a new condition or state change",
        affects="Condition Number",
    ),
    "SH": SIAEvent(
        code="SH",
        name="Sprinkler Alarm Restore",
        description="Alarm condition eliminated",
        affects="Zone",
    ),
    "SJ": SIAEvent(
        code="SJ",
        name="Sprinkler Trouble Restore",
        description="Trouble condition eliminated",
        affects="Zone",
    ),
    "SR": SIAEvent(
        code="SR",
        name="Sprinkler Restoral",
        description="Alarm/trouble condition has been eliminated",
        affects="Zone",
    ),
    "SS": SIAEvent(
        code="SS",
        name="Sprinkler Supervisory",
        description="Unsafe sprinkler system condition",
        affects="Zone",
    ),
    "ST": SIAEvent(
        code="ST",
        name="Sprinkler Trouble",
        description="Zone disabled by fault",
        affects="Zone",
    ),
    "SU": SIAEvent(
        code="SU",
        name="Sprinkler Unbypass",
        description="Sprinkler zone bypass has been removed",
        affects="Zone",
    ),
    "TA": SIAEvent(
        code="TA",
        name="Tamper Alarm",
        description="Alarm equipment enclosure opened",
        affects="Zone",
    ),
    "TB": SIAEvent(
        code="TB",
        name="Tamper Bypass",
        description="Tamper detection has been bypassed",
        affects="Zone",
    ),
    "TC": SIAEvent(
        code="TC",
        name="All Points Tested",
        description="All point tested",
        affects=None,
    ),
    "TE": SIAEvent(
        code="TE",
        name="Test End",
        description="Communicator restored to operation",
        affects=None,
    ),
    "TH": SIAEvent(
        code="TH",
        name="Tamper Alarm Restore",
        description="An Expansion Device's tamper switch restores to normal from an Alarm state",
        affects=None,
    ),
    "TJ": SIAEvent(
        code="TJ",
        name="Tamper Trouble Restore",
        description="An Expansion Device's tamper switch restores to normal from a Trouble state",
        affects=None,
    ),
    "TP": SIAEvent(
        code="TP",
        name="Walk Test Point",
        description="This point was tested during a Walk Test",
        affects="Zone",
    ),
    "TR": SIAEvent(
        code="TR",
        name="Tamper Restoral",
        description="Alarm equipment enclosure has been closed",
        affects="Zone",
    ),
    "TS": SIAEvent(
        code="TS",
        name="Test Start",
        description="Communicator taken out of operation",
        affects=None,
    ),
    "TT": SIAEvent(
        code="TT",
        name="Tamper Trouble",
        description="Equipment enclosure opened in disarmed state",
        affects="Zone",
    ),
    "TU": SIAEvent(
        code="TU",
        name="Tamper Unbypass",
        description="Tamper detection bypass has been removed",
        affects="Zone",
    ),
    "TW": SIAEvent(
        code="TW",
        name="Area Watch Start",
        description="Area watch feature has been activated",
        affects=None,
    ),
    "TX": SIAEvent(
        code="TX",
        name="Test Report",
        description="An unspecified (manual or automatic) communicator test",
        affects=None,
    ),
    "TZ": SIAEvent(
        code="TZ",
        name="Area Watch End",
        description="Area watch feature has been deactivated",
        affects=None,
    ),
    "UA": SIAEvent(
        code="UA",
        name="Untyped Zone Alarm",
        description="Alarm condition from zone of unknown type",
        affects="Zone",
    ),
    "UB": SIAEvent(
        code="UB",
        name="Untyped Zone Bypass",
        description="Zone of unknown type has been bypassed",
        affects="Zone",
    ),
    "UG": SIAEvent(
        code="UG",
        name="Unverified Event - Untyped",
        description="A point assigned to a Cross Point group has gone into alarm but the Cross Point remained normal",
        affects="Zone",
    ),
    "UH": SIAEvent(
        code="UH",
        name="Untyped Alarm Restore",
        description="Alarm condition eliminated",
        affects="Zone",
    ),
    "UJ": SIAEvent(
        code="UJ",
        name="Untyped Trouble Restore",
        description="Trouble condition eliminated",
        affects="Zone",
    ),
    "UR": SIAEvent(
        code="UR",
        name="Untyped Zone Restoral",
        description="Alarm/trouble condition eliminated from zone of unknown type",
        affects="Zone",
    ),
    "US": SIAEvent(
        code="US",
        name="Untyped Zone Supervisory",
        description="Unsafe condition from zone of unknown type",
        affects="Zone",
    ),
    "UT": SIAEvent(
        code="UT",
        name="Untyped Zone Trouble",
        description="Trouble condition from zone of unknown type",
        affects="Zone",
    ),
    "UU": SIAEvent(
        code="UU",
        name="Untyped Zone Unbypass",
        description="Bypass on zone of unknown type has been removed",
        affects="Zone",
    ),
    "UX": SIAEvent(
        code="UX",
        name="Undefined",
        description="An undefined alarm condition has occurred",
        affects=None,
    ),
    "UY": SIAEvent(
        code="UY",
        name="Untyped Missing Trouble",
        description="A point or device which was not armed is now logically missing",
        affects="Zone",
    ),
    "UZ": SIAEvent(
        code="UZ",
        name="Untyped Missing Alarm",
        description="A point or device which was armed is now logically missing",
        affects="Zone",
    ),
    "VI": SIAEvent(
        code="VI",
        name="Printer Paper In",
        description="TRANSMITTER or RECEIVER paper in",
        affects="Printer",
    ),
    "VO": SIAEvent(
        code="VO",
        name="Printer Paper Out",
        description="TRANSMITTER or RECEIVER paper out",
        affects="Printer",
    ),
    "VR": SIAEvent(
        code="VR",
        name="Printer Restore",
        description="TRANSMITTER or RECEIVER trouble restored",
        affects="Printer",
    ),
    "VT": SIAEvent(
        code="VT",
        name="Printer Trouble",
        description="TRANSMITTER or RECEIVER trouble",
        affects="Printer",
    ),
    "VX": SIAEvent(
        code="VX",
        name="Printer Test",
        description="TRANSMITTER or RECEIVER test",
        affects="Printer",
    ),
    "VY": SIAEvent(
        code="VY",
        name="Printer Online",
        description="RECEIVER'S printer is now online",
        affects=None,
    ),
    "VZ": SIAEvent(
        code="VZ",
        name="Printer Offline",
        description="RECEIVER'S printer is now offline",
        affects=None,
    ),
    "WA": SIAEvent(
        code="WA",
        name="Water Alarm",
        description="Water detected at protected premises",
        affects="Zone",
    ),
    "WB": SIAEvent(
        code="WB",
        name="Water Bypass",
        description="Water detection has been bypassed",
        affects="Zone",
    ),
    "WH": SIAEvent(
        code="WH",
        name="Water Alarm Restore",
        description="Water alarm condition eliminated",
        affects="Zone",
    ),
    "WJ": SIAEvent(
        code="WJ",
        name="Water Trouble Restore",
        description="Water trouble condition eliminated",
        affects="Zone",
    ),
    "WR": SIAEvent(
        code="WR",
        name="Water Restoral",
        description="Water alarm/trouble condition has been eliminated",
        affects="Zone",
    ),
    "WS": SIAEvent(
        code="WS",
        name="Water Supervisory",
        description="Water unsafe water detection system condition",
        affects="Zone",
    ),
    "WT": SIAEvent(
        code="WT",
        name="Water Trouble",
        description="Water zone disabled by fault",
        affects="Zone",
    ),
    "WU": SIAEvent(
        code="WU",
        name="Water Unbypass",
        description="Water detection bypass has been removed",
        affects="Zone",
    ),
    "XA": SIAEvent(
        code="XA",
        name="Extra Account Report",
        description="CS RECEIVER has received an event from a non-existent account",
        affects=None,
    ),
    "XE": SIAEvent(
        code="XE",
        name="Extra Point",
        description="Panel has sensed an extra point not specified for this site",
        affects="Zone",
    ),
    "XF": SIAEvent(
        code="XF",
        name="Extra RF Point",
        description="Panel has sensed an extra RF point not specified for this site",
        affects="Zone",
    ),
    "XH": SIAEvent(
        code="XH",
        name="RF Interference Restoral",
        description="A radio device is no longer detecting RF Interference",
        affects="Receiver",
    ),
    "XI": SIAEvent(
        code="XI",
        name="Sensor Reset",
        description="A user has reset a sensor",
        affects="Zone",
    ),
    "XJ": SIAEvent(
        code="XJ",
        name="RF Receiver Tamper Restoral",
        description="A Tamper condition at a premises RF Receiver has been restored",
        affects="Receiver",
    ),
    "XL": SIAEvent(
        code="XL",
        name="Low Received Signal Strength",
        description="The RF signal strength of a reported event is below minimum level",
        affects="Receiver",
    ),
    "XM": SIAEvent(
        code="XM",
        name="Missing Alarm - Cross Point",
        description="Missing Alarm verified by Cross Point in Alarm (or missing)",
        affects="Zone",
    ),
    "XQ": SIAEvent(
        code="XQ",
        name="RF Interference",
        description="A radio device is detecting RF Interference",
        affects="Receiver",
    ),
    "XR": SIAEvent(
        code="XR",
        name="Transmitter Battery Restoral",
        description="Low battery has been corrected",
        affects="Zone",
    ),
    "XS": SIAEvent(
        code="XS",
        name="RF Receiver Tamper",
        description="A Tamper condition at a premises receiver is detected",
        affects="Receiver",
    ),
    "XT": SIAEvent(
        code="XT",
        name="Transmitter Battery Trouble",
        description="Low battery in wireless transmitter",
        affects="Zone",
    ),
    "XW": SIAEvent(
        code="XW",
        name="Forced Point",
        description="A point was forced out of the system at arm time",
        affects="Zone",
    ),
    "XX": SIAEvent(
        code="XX",
        name="Fail to Test",
        description="A specific test from a panel was not received",
        affects=None,
    ),
    "YA": SIAEvent(
        code="YA",
        name="Bell Fault",
        description="A trouble condition has been detected on a Local Bell, Siren, or Annunciator",
        affects=None,
    ),
    "YB": SIAEvent(
        code="YB",
        name="Busy Seconds",
        description="Percent of time receiver's line card is on-line",
        affects="Line Card",
    ),
    "YC": SIAEvent(
        code="YC",
        name="Communications Fail",
        description="RECEIVER and TRANSMITTER",
        affects=None,
    ),
    "YD": SIAEvent(
        code="YD",
        name="Receiver Line Card Trouble",
        description="A line card identified by the passed address is in trouble",
        affects="Line Card",
    ),
    "YE": SIAEvent(
        code="YE",
        name="Receiver Line Card Restored",
        description="A line card identified by the passed address is restored",
        affects="Line Card",
    ),
    "YF": SIAEvent(
        code="YF",
        name="Parameter Checksum Fail",
        description="System data corrupted",
        affects=None,
    ),
    "YG": SIAEvent(
        code="YG",
        name="Parameter Changed",
        description="A TRANSMITTER'S parameters have been changed",
        affects=None,
    ),
    "YH": SIAEvent(
        code="YH",
        name="Bell Restored",
        description="A trouble condition has been restored on a Local Bell, Siren, or Annunciator",
        affects=None,
    ),
    "YI": SIAEvent(
        code="YI",
        name="Overcurrent Trouble",
        description="An Expansion Device has detected an overcurrent condition",
        affects=None,
    ),
    "YJ": SIAEvent(
        code="YJ",
        name="Overcurrent Restore",
        description="An Expansion Device has restored from an overcurrent condition",
        affects=None,
    ),
    "YK": SIAEvent(
        code="YK",
        name="Communications Restoral",
        description="TRANSMITTER has resumed communication with a RECEIVER",
        affects=None,
    ),
    "YM": SIAEvent(
        code="YM",
        name="System Battery Missing",
        description="TRANSMITTER/RECEIVER battery is missing",
        affects=None,
    ),
    "YN": SIAEvent(
        code="YN",
        name="Invalid Report",
        description="TRANSMITTER has sent a packet with invalid data",
        affects=None,
    ),
    "YO": SIAEvent(
        code="YO",
        name="Unknown Message",
        description="An unknown message was received from automation or the printer",
        affects=None,
    ),
    "YP": SIAEvent(
        code="YP",
        name="Power Supply Trouble",
        description="TRANSMITTER/RECEIVER has a problem with the power supply",
        affects=None,
    ),
    "YQ": SIAEvent(
        code="YQ",
        name="Power Supply Restored",
        description="TRANSMITTER'S/RECEIVER'S power supply has been restored",
        affects=None,
    ),
    "YR": SIAEvent(
        code="YR",
        name="System Battery Restoral",
        description="Low battery has been corrected",
        affects=None,
    ),
    "YS": SIAEvent(
        code="YS",
        name="Communications Trouble",
        description="RECEIVER and TRANSMITTER",
        affects=None,
    ),
    "YT": SIAEvent(
        code="YT",
        name="System Battery Trouble",
        description="Low battery in control/communicator",
        affects=None,
    ),
    "YU": SIAEvent(
        code="YU",
        name="Diagnostic Error",
        description="An expansion/peripheral device is reporting a diagnostic error",
        affects="Condition Number",
    ),
    "YW": SIAEvent(
        code="YW",
        name="Watchdog Reset",
        description="The TRANSMITTER created an internal reset",
        affects=None,
    ),
    "YX": SIAEvent(
        code="YX",
        name="Service Required",
        description="A TRANSMITTER/RECEIVER needs service",
        affects=None,
    ),
    "YY": SIAEvent(
        code="YY",
        name="Status Report",
        description="This is a header for an account status report transmission",
        affects=None,
    ),
    "YZ": SIAEvent(
        code="YZ",
        name="Service Completed",
        description="Required TRANSMITTER / RECEIVER service completed",
        affects=None,
    ),
    "ZA": SIAEvent(
        code="ZA",
        name="Freeze Alarm",
        description="Low temperature detected at premises",
        affects="Zone",
    ),
    "ZB": SIAEvent(
        code="ZB",
        name="Freeze Bypass",
        description="Low temperature detection has been bypassed",
        affects="Zone",
    ),
    "ZH": SIAEvent(
        code="ZH",
        name="Freeze Alarm Restore",
        description="Alarm condition eliminated",
        affects="Zone",
    ),
    "ZJ": SIAEvent(
        code="ZJ",
        name="Freeze Trouble Restore",
        description="Trouble condition eliminated",
        affects="Zone",
    ),
    "ZR": SIAEvent(
        code="ZR",
        name="Freeze Restoral",
        description="Alarm/trouble condition has been eliminated",
        affects="Zone",
    ),
    "ZS": SIAEvent(
        code="ZS",
        name="Freeze Supervisory",
        description="Unsafe freeze detection system condition",
        affects="Zone",
    ),
    "ZT": SIAEvent(
        code="ZT",
        name="Freeze Trouble",
        description="Zone disabled by fault",
        affects="Zone",
    ),
    "ZU": SIAEvent(
        code="ZU",
        name="Freeze Unbypass",
        description="Low temperature detection bypass removed",
        affects="Zone",
    ),
}
